#!/bin/sh
case "$1" in
    "C-d")
        while read file; do
            if command -v trash-put > /dev/null 2>&1; then
                trash-put "$file"
            else
                trash=~/.local/share/Trash/files;
                mkdir -p "$trash"; 
                mv "$file" "$trash"
            fi
        done ;;
    "C-r") 
        magick "$file" -rotate 90 "$file" ;;
    "C-m") 
        while read file; do
            file=$(realpath "$file")
            files="$file $files"
        done
        while true; do
            open=$(ls -a -F | grep '/'| rofi -dmenu)
            if [ "$open" = "./" ]; then
                for file in $files; do
                    file=$(echo "$file" | sed 's/^ \{1,\}//g; s/ \{1,\}$//g;')
                    mv "$file" $(pwd) -i
                done
                exit 0
            elif [ -d "$open" ]; then
                cd "$open"
            else
                exit 0
            fi
        done
        ;;
esac
