#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                [ ! -d ~/trash ] && mkdir ~/trash; mv "$file" ~/trash ;;
        "C-r")
                magick "$file" -rotate 90 "$file" ;;
        esac
done
