#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
            [ ! -d ~/.local/share/Trash ] && mkdir ~/.local/share/Trash/; mv "$file" ~/.local/share/Trash/ ;;
        "C-r")
                magick "$file" -rotate 90 "$file" ;;
        esac
done
