set statusline=%<%f\ %h%w%m%r%=%-14.(%l/%L,%c%)\ %P

set encoding=utf-8

set number
"set relativenumber
set ruler
set colorcolumn=80
set cursorline
set bg=dark
set laststatus=2
set showcmd

set tabstop=4
set shiftwidth=4
set autoindent
set expandtab
autocmd FileType cpp,fortran setlocal tabstop=2 shiftwidth=2
"sintax highlight for algol 60 using pascal sintax higlight
au BufRead,BufNewFile *.a60 set filetype=pascal
autocmd FileType make setlocal noexpandtab
autocmd BufNewFile,BufRead *.tsv setlocal noexpandtab

set splitbelow
set splitright

set path+=**
set wildmenu
set tags=./tags,./TAGS,tags;~,TAGS;~

set ignorecase
set incsearch
set hlsearch
"set nowrapscan

set shortmess-=S

set smartindent
set foldmethod=indent
set foldlevelstart=20

set nrformats+=alpha

set hidden

set formatoptions+=j

"set spell
"set dictionary=~/.vim/dictionaries/eng-466550.txt,~/.vim/dictionaries/br-sem-acentos.txt

set viminfofile=$XDG_STATE_HOME/vim/viminfo


imap jk <Esc>


autocmd BufRead * let &l:modifiable = !&readonly

syntax on

let g:markdown_fenced_languages = ['basic', 'asm', 'c', 'cpp', 'python', 'javascript', 'typescript', 'php', 'ruby', 'perl', 'bash', 'sh', 'sed', 'awk', 'bc', 'vim', 'sql', 'html', 'xml', 'css', 'sass', 'less', 'lisp', 'scheme', 'haskell', 'dockerfile', 'yaml', 'json', 'tex', 'tmux', 'make']

" hide errors for comments in json files
autocmd FileType json syntax match Comment +\/\/.\+$+
autocmd FileType json syntax match Comment +\/\*.\+\*\/+

colorscheme slate
hi ColorColumn ctermbg=237
hi Visual cterm=reverse ctermfg=109 ctermbg=234
hi Search cterm=reverse ctermfg=74 ctermbg=234
hi IncSearch cterm=reverse ctermfg=215 ctermbg=234
hi Error cterm=reverse ctermfg=131 ctermbg=234
hi ErrorMsg cterm=reverse ctermfg=131 ctermbg=234

"colorscheme habamax
"colorscheme sorbet 
"colorscheme desert
"colorscheme wildcharm
