set statusline=%<%f\ %h%w%m%r%=%-14.(%l/%L,%c%)\ %P

set encoding=utf-8

set number
"set relativenumber
set ruler
set colorcolumn=80
set cursorline
set bg=dark
set laststatus=2
set showcmd

set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
autocmd FileType cpp,fortran setlocal tabstop=2 shiftwidth=2
autocmd FileType make setlocal noexpandtab
autocmd BufNewFile,BufRead *.tsv setlocal noexpandtab

set splitbelow
set splitright

set path+=**
set wildmenu
set tags=./tags,./TAGS,tags;~,TAGS;~

set ignorecase
set smartcase "case sensitive search if the search pattern contains upper case characters
set incsearch
set hlsearch
"set nowrapscan

set shortmess-=S "show search count message when searching

set smartindent
set foldmethod=indent
set foldlevelstart=20

set nrformats+=alpha

set hidden

set formatoptions+=j

"set spell
"set dictionary=~/.vim/dictionaries/eng-466550.txt,~/.vim/dictionaries/br-sem-acentos.txt

set viminfofile=$XDG_STATE_HOME/vim/viminfo


imap jk <Esc>


autocmd BufRead * let &l:modifiable = !&readonly

syntax on
au BufRead,BufNewFile *.a60 set filetype=pascal "sintax highlight for algol 60 using pascal's one

let g:markdown_fenced_languages  = ['asm', 'c', 'cpp']
let g:markdown_fenced_languages += ['java']
let g:markdown_fenced_languages += ['basic']
let g:markdown_fenced_languages += ['javascript', 'typescript', 'php', 'ruby', 'python']
let g:markdown_fenced_languages += ['perl', 'bash', 'sh', 'sed', 'awk', 'bc']
let g:markdown_fenced_languages += ['vim']
let g:markdown_fenced_languages += ['tex', 'html', 'css', 'sass', 'less']
let g:markdown_fenced_languages += ['sql']
let g:markdown_fenced_languages += ['lisp', 'scheme', 'haskell']
let g:markdown_fenced_languages += ['tmux', 'make', 'dockerfile', 'xml', 'yaml', 'json']

"hide errors for comments in json files
autocmd FileType json syntax match Comment +\/\/.\+$+
autocmd FileType json syntax match Comment +\/\*.\+\*\/+

colorscheme slate
hi ColorColumn ctermbg=237
hi Visual cterm=reverse ctermfg=109 ctermbg=234
hi Search cterm=reverse ctermfg=74 ctermbg=234
hi IncSearch cterm=reverse ctermfg=215 ctermbg=234
hi Error cterm=bold,reverse ctermfg=167 ctermbg=235
hi ErrorMsg cterm=bold ctermfg=235 ctermbg=167
autocmd FileType c,cpp hi! link Structure Type "c/c++ struct, class, etc. the same as int, float, etc.
autocmd FileType c,cpp hi! link Statement Include

"colorscheme habamax
"dolorscheme sorbet 
"colorscheme desert
"colorscheme wildcharm
