unbind C-b
set -g prefix C-j
bind C-j send-prefix

bind C-n next-window
bind C-p previous-window

bind -n M-n next-window
bind -n M-p previous-window

bind -n M-N swap-window -t +1 \; select-window -t +1
bind -n M-P swap-window -t -1 \; select-window -t -1

bind -n M-1 select-window -t 1 
bind -n M-2 select-window -t 2 
bind -n M-3 select-window -t 3 
bind -n M-4 select-window -t 4 
bind -n M-5 select-window -t 5 
bind -n M-6 select-window -t 6 
bind -n M-7 select-window -t 7 
bind -n M-8 select-window -t 8 
bind -n M-9 select-window -t 9 

set -gw mode-keys vi
set -g status-keys emacs
set -g base-index 1
set -g renumber-windows on
set -g status-style "fg=#ffffff,bg=#000000"
set -gw window-status-current-style "fg=#000000,bg=#66d9ef"
set -g history-file ~/.local/state/tmux/tmux_history

bind e source-file "~/.config/tmux/tmux.conf"
# bind b set -g status
# bind-key -n M-BSpace send-keys C-w

bind F run "tmux neww ~/.local/bin/tmux-session-dispensary.sh" # f: command-prompt { find-window -Z "%%" }
# bind g run "~/.local/bin/open-github.sh"
# bind t run "tmux neww ~/.local/bin/time.sh" # t: clock-mode (show clock fullscreen)
bind H run "~/.local/bin/tmux-session-dispensary.sh ~"
bind N run "~/.local/bin/tmux-session-dispensary.sh ~/notas"
bind P run "~/.local/bin/tmux-session-dispensary.sh ~/dev"  # Project, Programming, D: choose-client -Z
bind W run "~/.local/bin/tmux-session-dispensary.sh ~/dwnlds"   # doWnloads
bind T run "~/.local/bin/tmux-session-dispensary.sh ~/tmp"
bind B run "~/.local/bin/tmux-session-dispensary.sh ~/docs/livros"  # Books
bind O run "~/.local/bin/tmux-session-dispensary.sh ~/.config"  # cOnfig, C: customize-mode -Z
bind R run "~/.local/bin/tmux-session-dispensary.sh ~/.dotfiles"    # R de rc, D: choose-client -Z
bind b run "~/.local/bin/tmux-session-dispensary.sh ~/.local/bin"
bind S run "~/.local/bin/tmux-session-dispensary.sh ~/.local/share"
bind A run "~/.local/bin/tmux-session-dispensary.sh ~/.local/state" # stAte, (XDG_DATA_HOME)
bind V run "~/.local/bin/tmux-session-dispensary.sh ~/.config/nvim"

bind T run-shell "tmux has-session -t top 2>/dev/null && tmux switch-client -t top || tmux new-session -d -s top -c $HOME 'top -o %MEM; $SHELL' \\; switch-client -t top"

#  .local, 
bind G neww -n "git" -S lazygit
# bind E show-environment -g    # E: select-layout -E
# bind o neww -S -n "BOOK" "nvim -R ~/bookmarks.csv" # o: select-pane -t :.+ (other pane) 
