#!/bins/sh

# wm=twm
# wm=openbox
wm=i3
# wm=dwm
# wm=bspwm
# wm=xmonad 
# wm=qtile
# wm=awesome

if [ "$wm" == dwm ]; then
    $HOME/.local/bin/dwm-bar.sh
fi

xrdb -merge ~/.config/x11/xresources

if [ "$wm" == qtile ]; then
    qtile start 
else
    exec "$wm"
fi
