# /etc/bash.bashrc or /etc/bashrc must contain this line:
# source "$HOME"/.config/bash/bashrc

#export TERM='xterm-256color'
export PS1='\[\033[1;94m\]\u@\h:\w\[\033[00m\]$ '
export HISTCONTROL="ignoreboth:erasedups"
export EDITOR='/usr/bin/vim'

# XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export HISTFILE="$XDG_STATE_HOME"/bash/history
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export SCREENDIR="${XDG_RUNTIME_DIR}/screen"
export SCREENRC="$XDG_CONFIG_HOME"/screen/screenrc
export SQLITE_HISTORY="$XDG_STATE_HOME"/sqlite_history
export PYTHON_HISTORY="$XDG_STATE_HOME"/python_history
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME"/python
export PYTHONUSERBASE="$XDG_DATA_HOME"/python
export W3M_DIR="$XDG_STATE_HOME"/w3m

#export LESS='-R --use-color -Dd+r$Du+b'
export LESS='-R'
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline

export LC_COLLATE="C"

alias ls='ls --color --group-directories-first'
alias grep='grep --color'

! vi --version &> /dev/null && alias vi='vim'
! view --version &> /dev/null && alias view='vi -R'

alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

shopt -s extglob;

# disable terminal freezing with Ctrl + s, allowing to do a forward-search-history with Ctrl + s
stty -ixon

eval $(keychain --eval --quiet --absolute --dir "$XDG_RUNTIME_DIR"/keychain)
